language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.1
    - android-25
    - platform-tools

    - extra-android-m2repository

notifications:
  email: false
